### ISSUE TITLE
Can't use keyboard for digits only 

### ISSUE THREAD

**Issue by psyhitus** [TinkoffCreditSystems/decoro#5]
Trying to set 
`editText.setInputType(InputType.TYPE_CLASS_PHONE);`

and decoro doesn't work. I don't know it can be is not problem of your library, may be its Android default behaviour 

Expacted result:
![2016-11-01_17-02-01](https://cloud.githubusercontent.com/assets/537337/19892295/38a7169a-a055-11e6-91fe-c003ab2751aa.png)

Actual result:
![2016-11-01_17-02-50](https://cloud.githubusercontent.com/assets/537337/19892287/33aa8f8c-a055-11e6-8459-69d18ad915b6.png)

Thanks for making our dev's life simpler :+1:

**Comment by meandnano** [comment]
I don't see a problem on your screenshots.

But yes, there's one important thing about InputTypes in Android. If you'll set input type of your EditText to InputType.TYPE_CLASS_NUMBER you won't be able to use a mask with non-digit characters. This happens because Android won't let you put any non-digit character to EditText and Decoro won't work. This is the limitation of the platform.

That's why you should set input type to InputType.TYPE_CLASS_PHONE if you using mask for phone number, card number, date etc.

**Comment by psyhitus** [comment]
Thanks for your answer. I think i know some workarounds how to do it, but i think its not so mission critical problem :)

**Comment by vkotovv** [comment]
@meandnano Probably you should mention this workaround (usage of `TYPE_CLASS_PHONE` if mask is not a digit) in Readme, in Known issues or somewhere else.
